const sampleData = {
  users: [
    {
      name: 'admin',
      username: 'admin',
      email: 'admin@example.com',
      phone: '0900000000',
      password: 'Admin123',
      role: 'admin',
    },
    {
      name: 'user',
      username: 'user',
      email: 'user@example.com',
      phone: '0911111111',
      password: '123456',
      role: 'user',
    },
    {
      name: 'nguyenminh',
      username: 'nguyenminh',
      email: 'nguyenminh@prostore.local',
      phone: '0901234567',
      password: '123456',
      role: 'user',
    },
    {
      name: 'thanhha',
      username: 'thanhha',
      email: 'thanhha@prostore.local',
      phone: '0912345678',
      password: '123456',
      role: 'user',
    },
    {
      name: 'hoangnam',
      username: 'hoangnam',
      email: 'hoangnam@prostore.local',
      phone: '0923456789',
      password: '123456',
      role: 'user',
    },
    {
      name: 'linhchi',
      username: 'linhchi',
      email: 'linhchi@prostore.local',
      phone: '0934567890',
      password: '123456',
      role: 'user',
    },
  ],
  orders: [
    { id: 'sample-order-006', userId: 'sample-user-5', user: { name: 'linhchi' }, totalPrice: '18790000', itemsPrice: '18760000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'BankTransfer', isPaid: true, paidAt: new Date('2026-09-22T09:20:00+07:00'), isDelivered: false, deliveredAt: null, createdAt: new Date('2026-09-22T09:12:00+07:00') },
    { id: 'sample-order-005', userId: 'sample-user-4', user: { name: 'hoangnam' }, totalPrice: '5320000', itemsPrice: '5290000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'CashOnDelivery', isPaid: false, paidAt: null, isDelivered: false, deliveredAt: null, createdAt: new Date('2026-09-21T15:35:00+07:00') },
    { id: 'sample-order-004', userId: 'sample-user-3', user: { name: 'thanhha' }, totalPrice: '10490000', itemsPrice: '10460000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'BankTransfer', isPaid: true, paidAt: new Date('2026-09-20T11:10:00+07:00'), isDelivered: true, deliveredAt: new Date('2026-09-22T14:30:00+07:00'), createdAt: new Date('2026-09-20T10:55:00+07:00') },
    { id: 'sample-order-003', userId: 'sample-user-2', user: { name: 'nguyenminh' }, totalPrice: '4720000', itemsPrice: '4690000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'CashOnDelivery', isPaid: true, paidAt: new Date('2026-09-19T16:45:00+07:00'), isDelivered: true, deliveredAt: new Date('2026-09-19T16:45:00+07:00'), createdAt: new Date('2026-09-17T08:25:00+07:00') },
    { id: 'sample-order-002', userId: 'sample-user-1', user: { name: 'user' }, totalPrice: '2420000', itemsPrice: '2390000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'BankTransfer', isPaid: true, paidAt: new Date('2026-09-15T13:40:00+07:00'), isDelivered: false, deliveredAt: null, createdAt: new Date('2026-09-15T13:30:00+07:00') },
    { id: 'sample-order-001', userId: 'sample-user-2', user: { name: 'nguyenminh' }, totalPrice: '1020000', itemsPrice: '990000', shippingPrice: '30000', taxPrice: '0', paymentMethod: 'CashOnDelivery', isPaid: false, paidAt: null, isDelivered: false, deliveredAt: null, createdAt: new Date('2026-09-12T19:05:00+07:00') },
  ],
  products: [
    {
      name: 'CPU Intel Core i5-14400F (LGA 1700, 10 nhân 16 luồng, Turbo 4.7GHz)',
      slug: 'cpu-intel-core-i5-14400f',
      category: 'CPU',
      description:
        'Bộ vi xử lý Intel Core i5-14400F thế hệ 14 Raptor Lake Refresh mang lại hiệu năng ấn tượng cho cả chơi game và làm việc đồ họa. Với 10 nhân (6 P-Core + 4 E-Core) và 16 luồng xử lý, xung nhịp tối đa lên tới 4.7GHz. Tương thích chuẩn socket LGA 1700 và hỗ trợ cả RAM DDR4 lẫn DDR5.\n\nBảo hành chính hãng 36 tháng. Đầy đủ quạt tản nhiệt đi kèm.',
      images: [
        '/images/hardware/cpu-i5.jpg',
      ],
      price: 4690000,
      brand: 'Intel',
      rating: 4.9,
      numReviews: 18,
      stock: 25,
      isFeatured: true,
      banner: '/images/hardware/cpu-i5.jpg',
    },
    {
      name: 'CPU AMD Ryzen 5 7600 (Socket AM5, 6 nhân 12 luồng, Turbo 5.1GHz)',
      slug: 'cpu-amd-ryzen-5-7600',
      category: 'CPU',
      description:
        'CPU AMD Ryzen 5 7600 kiến trúc Zen 4 tiến trình 5nm vượt trội, hỗ trợ socket AM5 với chuẩn RAM DDR5 và PCIe 5.0 thế hệ mới. Hiệu năng đơn nhân và đa nhân mạnh mẽ, tích hợp sẵn nhân đồ họa AMD Radeon Graphics.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/cpu-i5.jpg',
      ],
      price: 5290000,
      brand: 'AMD',
      rating: 4.8,
      numReviews: 12,
      stock: 18,
      isFeatured: true,
      banner: '/images/hardware/cpu-i5.jpg',
    },
    {
      name: 'Mainboard ASUS TUF GAMING B760M-PLUS WIFI DDR5',
      slug: 'mainboard-asus-tuf-gaming-b760m-plus-wifi-ddr5',
      category: 'Mainboard',
      description:
        'Bo mạch chủ ASUS TUF GAMING B760M-PLUS WIFI chuẩn mATX thiết kế bền bỉ chuẩn quân đội TUF. Hệ thống cấp điện 12+1 DrMOS tản nhiệt VRM dày dặn, hỗ trợ RAM DDR5 lên đến 7200+(OC) MHz, 2 khe M.2 PCIe 4.0, kết nối Wi-Fi 6 và mạng Realtek 2.5Gb Ethernet.\n\nBảo hành 36 tháng chính hãng ASUS.',
      images: [
        '/images/hardware/mainboard-b760.jpg',
      ],
      price: 3990000,
      brand: 'ASUS',
      rating: 4.7,
      numReviews: 9,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Card màn hình ASUS Dual GeForce RTX 4060 EVO OC 8GB GDDR6',
      slug: 'vga-asus-dual-geforce-rtx-4060-evo-oc-8gb',
      category: 'VGA',
      description:
        'Card đồ họa ASUS Dual GeForce RTX 4060 EVO OC 8GB sử dụng kiến trúc NVIDIA Ada Lovelace tân tiến, mang đến công nghệ dò tia Ray Tracing và nhân AI DLSS 3 đột phá. 2 quạt công nghệ Axial-tech vòng bi kép êm ái, backplate bảo vệ bằng nhôm gia cố chắc chắn.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/vga-rtx4060.jpg',
      ],
      price: 7990000,
      brand: 'ASUS',
      rating: 4.9,
      numReviews: 24,
      stock: 16,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Card màn hình Gigabyte GeForce RTX 4070 SUPER WINDFORCE OC 12GB',
      slug: 'vga-gigabyte-rtx-4070-super-windforce-oc-12gb',
      category: 'VGA',
      description:
        'Sức mạnh xử lý đồ họa đỉnh cao với GPU RTX 4070 SUPER 12GB GDDR6X băng thông 192-bit. Hệ thống làm mát 3 quạt WINDFORCE xoay đảo chiều độc quyền, tản nhiệt ống đồng tiếp xúc trực tiếp. Cân mượt mà mọi tựa game 2K và 4K ở thiết lập Ultra.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/vga-rtx4060.jpg',
      ],
      price: 17890000,
      brand: 'Gigabyte',
      rating: 5.0,
      numReviews: 15,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'RAM Kingston Fury Beast RGB 32GB (2x16GB) DDR5 5600MHz',
      slug: 'ram-kingston-fury-beast-rgb-32gb-ddr5-5600mhz',
      category: 'RAM',
      description:
        'Bộ kit RAM Kingston Fury Beast RGB chuẩn DDR5 thế hệ mới dung lượng 32GB (2 thanh 16GB), bus 5600MHz CL36. Hệ thống đèn LED RGB rực rỡ đồng bộ tùy biến, hỗ trợ công nghệ Intel XMP 3.0 và AMD EXPO giúp ép xung mượt mà và ổn định.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/ram-ddr5.jpg',
      ],
      price: 2690000,
      brand: 'Kingston',
      rating: 4.8,
      numReviews: 14,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'RAM Corsair Vengeance LPX 16GB (1x16GB) DDR4 3200MHz',
      slug: 'ram-corsair-vengeance-lpx-16gb-ddr4-3200mhz',
      category: 'RAM',
      description:
        'Bộ nhớ trong Corsair Vengeance LPX 16GB DDR4 3200MHz thiết kế tản nhiệt nhôm nguyên chất giúp tản nhiệt nhanh chóng, chiều cao thấp tương thích với hầu hết các mẫu tản nhiệt khí lớn. Hỗ trợ Intel XMP 2.0 ép xung tự động an toàn.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/ram-ddr5.jpg',
      ],
      price: 890000,
      brand: 'Corsair',
      rating: 4.6,
      numReviews: 28,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Ổ cứng SSD Samsung 990 EVO 1TB M.2 PCIe Gen 4.0 x4 / Gen 5.0 x2 NVMe',
      slug: 'ssd-samsung-990-evo-1tb-nvme',
      category: 'SSD',
      description:
        'Ổ cứng SSD Samsung 990 EVO 1TB sở hữu tốc độ đọc tuần tự lên đến 5.000 MB/s và ghi tuần tự 4.200 MB/s. Hỗ trợ linh hoạt cả hai chuẩn giao tiếp PCIe 4.0 và PCIe 5.0, tiết kiệm điện năng đến 70% so với thế hệ trước 970 EVO Plus.\n\nBảo hành chính hãng 60 tháng (5 năm).',
      images: [
        '/images/hardware/ssd-980pro.jpg',
      ],
      price: 2390000,
      brand: 'Samsung',
      rating: 4.9,
      numReviews: 20,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Ổ cứng SSD Kingston NV2 500GB M.2 2280 PCIe Gen 4.0 x4 NVMe',
      slug: 'ssd-kingston-nv2-500gb-nvme',
      category: 'SSD',
      description:
        'SSD Kingston NV2 500GB PCIe 4.0 NVMe là giải pháp nâng cấp lưu trữ tối ưu chi phí cho máy tính bàn và laptop. Tốc độ đọc lên tới 3.500 MB/s và ghi 2.100 MB/s, kích thước nhỏ gọn chuẩn M.2 2280.\n\nBảo hành chính hãng 36 tháng.',
      images: [
        '/images/hardware/ssd-980pro.jpg',
      ],
      price: 990000,
      brand: 'Kingston',
      rating: 4.5,
      numReviews: 35,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nguồn máy tính Corsair RM750e 750W 80 Plus Gold Fully Modular',
      slug: 'nguon-corsair-rm750e-750w-80-plus-gold',
      category: 'PSU',
      description:
        'Nguồn máy tính Corsair RM750e đạt chứng nhận chuẩn 80 Plus Gold và Cybenetics Platinum về hiệu suất năng lượng. Dây cáp rời hoàn toàn Fully Modular, quạt làm mát 120mm công nghệ Rifle Bearing vận hành tĩnh lặng, chuẩn ATX 3.0 và PCIe 5.0.\n\nBảo hành chính hãng 84 tháng (7 năm).',
      images: [
        '/images/hardware/psu-rm750e.jpg',
      ],
      price: 2790000,
      brand: 'Corsair',
      rating: 4.8,
      numReviews: 11,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Vỏ Case Montech AIR 100 ARGB Black (Kèm sẵn 4 Quạt ARGB)',
      slug: 'case-montech-air-100-argb-black',
      category: 'Case',
      description:
        'Vỏ case mini-tower Montech AIR 100 ARGB Black mặt trước lưới tổ ong thông thoáng tối đa, cửa sổ hông kính cường lực dạng bản lề mở đóng tiện lợi. Đi kèm sẵn 4 quạt tản nhiệt ARGB 120mm và bộ hub điều khiển hiệu ứng ánh sáng.\n\nBảo hành 12 tháng.',
      images: [
        '/images/hardware/case-gaming.jpg',
      ],
      price: 1190000,
      brand: 'Montech',
      rating: 4.7,
      numReviews: 16,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'PC Gaming Phước Long Core i5-13400F / RTX 4060 8GB / 16GB DDR5 / SSD 512GB',
      slug: 'pc-gaming-phuoc-long-i5-13400f-rtx-4060',
      category: 'PC',
      description:
        'Cấu hình PC Gaming được Vi Tính Phước Long tinh chỉnh và tối ưu hóa sẵn sàng chiến mượt mọi tựa game Esports và AAA (PUBG, Valorant, GTA V, Black Myth: Wukong, Cyberpunk 2077 ở độ phân giải FHD và 2K).\n\n- CPU: Intel Core i5-13400F (10 nhân, 16 luồng)\n- RAM: 16GB DDR5 5200MHz\n- VGA: NVIDIA GeForce RTX 4060 8GB GDDR6\n- Ổ cứng: SSD 512GB M.2 NVMe PCIe 4.0\n- Nguồn: 650W 80 Plus Bronze\n- Vỏ case: Kính cường lực kèm 3 Fan LED RGB\n\nBảo hành tận nơi 36 tháng. Miễn phí công ráp máy và cài đặt phần mềm trọn đời.',
      images: [
        '/images/hardware/pc-gaming.jpg',
      ],
      price: 18500000,
      brand: 'Phước Long PC',
      rating: 5.0,
      numReviews: 32,
      stock: 10,
      isFeatured: true,
      banner: '/images/hardware/pc-gaming.jpg',
    },
  ],
};

export default sampleData;
